version: "3.9"
services:
  mongo:
    image: "mongo:4.2.16"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mysql:
    image: "mysql:8.0.26"
    restart: unless-stopped
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  mongo:
  mysql:
